[package]
name = "unchecked-refcell"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.4"

[features]
default = []
debug_refcell = []
checked = ["debug_refcell"]

[[bench]]
name = "bench"
harness = false